server {
  listen 80;
  root /usr/share/nginx/html;
  charset utf-8;
  sendfile off;
  add_header Cache-Control "no-store";
  location = / { try_files /index.html =404; }
  location ~ ^/(?:[a-zA-Z0-9_-]+\.html|(?:css|js|images)/.+)$ { try_files $uri =404; }
  location / { return 404; }
}
